name: Release Drafter (Draft Only)
on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  update_draft:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
