name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Get Next Version (SemVer)
        id: version
        uses: paulhatch/semantic-version@v6.0.2
        with:
          branch: develop

      - name: Create Release and Tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version_tag }}
          token: ${{ github.token }}
